apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-sample-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: application-sample-3
  name: component-sample-3
  namespace: maysun
spec:
  ports:
  - port: 5566
    targetPort: 5566
  selector:
    app.kubernetes.io/instance: component-sample-3
status:
  loadBalancer: {}
